spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easybank?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  config:
    import: application_prod.yml

  profiles:
    active: default


  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update # 'create', 'update', 'validate', 'none' 중 선택
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 이상에 맞는 Dialect
        format_sql: true


logging:
  level:
    org.springframework.security : TRACE
    org.hibernate.SQL: debug


server:
  servlet:
    session:
      timeout: 2m




