spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easybank?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: prod


  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none # 'create', 'update', 'validate', 'none' 중 선택
      show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 이상에 맞는 Dialect
        format_sql: false


logging:
  level:
    org.springframework.security : Error
    org.hibernate.SQL: debug


